/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.conversor.views;

import com.conversor.operaciones.DivisasOperations;
import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Zeckre
 */
public class Divisas extends javax.swing.JPanel {

    /**
     * Creates new form Divisas
     */
    
    Double convertText;
    int var2, var1;
    
    public Divisas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divBackgroud = new javax.swing.JPanel();
        textOne = new javax.swing.JLabel();
        textTwo = new javax.swing.JLabel();
        valueTwo = new javax.swing.JComboBox<>();
        valueOne = new javax.swing.JComboBox<>();
        valueIn = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        textThree = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valueOut = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(454, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(454, 500));

        divBackgroud.setMinimumSize(new java.awt.Dimension(454, 500));
        divBackgroud.setPreferredSize(new java.awt.Dimension(454, 500));

        textOne.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        textOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne.setText("Convert ");

        textTwo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        textTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTwo.setText("to");

        valueTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COP", "EUR", "KRW", "GBP", "USD", "JPY" }));
        valueTwo.setBorder(null);
        valueTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        valueTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTwoActionPerformed(evt);
            }
        });

        valueOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COP", "EUR", "KRW", "GBP", "USD", "JPY" }));
        valueOne.setBorder(null);
        valueOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        valueOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueOneActionPerformed(evt);
            }
        });

        valueIn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        valueIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valueIn.setBorder(null);
        valueIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueInActionPerformed(evt);
            }
        });

        btnConvert.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnConvert.setText("Convert now!");
        btnConvert.setBorder(null);
        btnConvert.setBorderPainted(false);
        btnConvert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        textThree.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        textThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textThree.setText("Enter currency value");

        valueOut.setColumns(20);
        valueOut.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        valueOut.setRows(5);
        valueOut.setBorder(null);
        jScrollPane1.setViewportView(valueOut);

        javax.swing.GroupLayout divBackgroudLayout = new javax.swing.GroupLayout(divBackgroud);
        divBackgroud.setLayout(divBackgroudLayout);
        divBackgroudLayout.setHorizontalGroup(
            divBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(divBackgroudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divBackgroudLayout.createSequentialGroup()
                        .addComponent(valueTwo, 0, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueOne, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divBackgroudLayout.createSequentialGroup()
                        .addComponent(textThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divBackgroudLayout.createSequentialGroup()
                        .addGroup(divBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConvert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valueIn))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divBackgroudLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        divBackgroudLayout.setVerticalGroup(
            divBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divBackgroudLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(textOne, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(divBackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valueOne)
                    .addComponent(valueTwo)
                    .addComponent(textTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(textThree, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueIn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed

        //Obtenemos cada uno de los elementos
        convertText = Double.valueOf(valueIn.getText());
        var1 = valueTwo.getSelectedIndex();
        var2 = valueOne.getSelectedIndex();
        
        //Puente
        DivisasOperations divop = new DivisasOperations();
        
        //Envio los valores hacia el documento donde se realizan las operaciones
        divop.setVar1(var1);
        divop.setVar2(var2);
        divop.setConvertText(convertText);        
        
        //Texto de salida
        DecimalFormat df = new DecimalFormat("#.000000");
        valueOut.append("" + df.format(divop.convertirValue()));
    }//GEN-LAST:event_btnConvertActionPerformed

    private void valueInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueInActionPerformed

    private void valueOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueOneActionPerformed

    private void valueTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueTwoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JPanel divBackgroud;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textOne;
    private javax.swing.JLabel textThree;
    private javax.swing.JLabel textTwo;
    private javax.swing.JTextField valueIn;
    private javax.swing.JComboBox<String> valueOne;
    private javax.swing.JTextArea valueOut;
    private javax.swing.JComboBox<String> valueTwo;
    // End of variables declaration//GEN-END:variables
}
