/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.conversor.views;

/**
 *
 * @author Zeckre
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Divisas
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divBackgroud = new javax.swing.JPanel();
        textOne = new javax.swing.JLabel();
        textOne1 = new javax.swing.JLabel();
        textOne2 = new javax.swing.JLabel();
        textOne3 = new javax.swing.JLabel();
        textOne4 = new javax.swing.JLabel();
        textOne5 = new javax.swing.JLabel();
        textOne6 = new javax.swing.JLabel();
        textOne7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(454, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(454, 500));

        divBackgroud.setMinimumSize(new java.awt.Dimension(454, 500));
        divBackgroud.setPreferredSize(new java.awt.Dimension(454, 500));
        divBackgroud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textOne.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne.setText("que desee realizar.");
        divBackgroud.add(textOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 454, 38));

        textOne1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne1.setText("¡BIENVENIDO!");
        divBackgroud.add(textOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 454, 38));

        textOne2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne2.setText("En este convertidor podra convertir,");
        divBackgroud.add(textOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 454, 38));

        textOne3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne3.setText("diferentes valores de divisas,");
        divBackgroud.add(textOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 454, 38));

        textOne4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne4.setText("asi como temperaturas de celsius a ");
        divBackgroud.add(textOne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 454, 38));

        textOne5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne5.setText("grados fahrenheit, o viceversa");
        divBackgroud.add(textOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 454, 38));

        textOne6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne6.setText("asi mismo como diferentes longitudes");
        divBackgroud.add(textOne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 454, 38));

        textOne7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textOne7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOne7.setText("En el menu puede elegir la conversión ");
        divBackgroud.add(textOne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 454, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel divBackgroud;
    private javax.swing.JLabel textOne;
    private javax.swing.JLabel textOne1;
    private javax.swing.JLabel textOne2;
    private javax.swing.JLabel textOne3;
    private javax.swing.JLabel textOne4;
    private javax.swing.JLabel textOne5;
    private javax.swing.JLabel textOne6;
    private javax.swing.JLabel textOne7;
    // End of variables declaration//GEN-END:variables
}
