/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.conversordivisas;

import com.conversor.views.Divisas;
import com.conversor.views.Longitudes;
import com.conversor.views.Principal;
import com.conversor.views.Temperatura;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatDraculaIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Zeckre
 */
public class igConversor extends javax.swing.JFrame {

    /**
     * Creates new form igConversor
     */
    public igConversor() {
        initComponents();
        InitContent();
      
    }
   

    private void ShowJPanels(JPanel p) {
        p.setSize(454,500);
        p.setLocation(0,0);
        
        body.removeAll();
        body.add(p, BorderLayout.CENTER);
        body.revalidate();
        body.repaint();
    }
    
    private void InitContent(){
        ShowJPanels(new Principal());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        byZeckre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDivisas = new javax.swing.JButton();
        btnTemperature = new javax.swing.JButton();
        btnMedidas = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jToolBar3 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(716, 540));

        backgroud.setBackground(new java.awt.Color(255, 255, 255));
        backgroud.setMinimumSize(new java.awt.Dimension(716, 540));
        backgroud.setPreferredSize(new java.awt.Dimension(716, 540));

        body.setPreferredSize(new java.awt.Dimension(466, 500));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        menu.setBackground(new java.awt.Color(149, 128, 255));
        menu.setPreferredSize(new java.awt.Dimension(250, 500));

        byZeckre.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        byZeckre.setForeground(new java.awt.Color(60, 63, 65));
        byZeckre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        byZeckre.setText("By Zeckre");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("iConversor");

        btnDivisas.setBackground(new java.awt.Color(154, 133, 250));
        btnDivisas.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnDivisas.setForeground(new java.awt.Color(60, 63, 65));
        btnDivisas.setText("Divisas");
        btnDivisas.setBorder(new javax.swing.border.MatteBorder(null));
        btnDivisas.setBorderPainted(false);
        btnDivisas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisasActionPerformed(evt);
            }
        });

        btnTemperature.setBackground(new java.awt.Color(154, 133, 250));
        btnTemperature.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnTemperature.setForeground(new java.awt.Color(60, 63, 65));
        btnTemperature.setText("Temperatura");
        btnTemperature.setBorder(new javax.swing.border.MatteBorder(null));
        btnTemperature.setBorderPainted(false);
        btnTemperature.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperatureActionPerformed(evt);
            }
        });

        btnMedidas.setBackground(new java.awt.Color(154, 133, 250));
        btnMedidas.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnMedidas.setForeground(new java.awt.Color(60, 63, 65));
        btnMedidas.setText("Medidas");
        btnMedidas.setBorder(new javax.swing.border.MatteBorder(null));
        btnMedidas.setBorderPainted(false);
        btnMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedidasActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        jToolBar3.setBackground(new java.awt.Color(255, 128, 191));
        jToolBar3.setRollover(true);

        jToolBar2.setForeground(new java.awt.Color(60, 63, 65));
        jToolBar2.setRollover(true);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(byZeckre, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDivisas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(byZeckre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout backgroudLayout = new javax.swing.GroupLayout(backgroud);
        backgroud.setLayout(backgroudLayout);
        backgroudLayout.setHorizontalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroudLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroudLayout.setVerticalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedidasActionPerformed
        // TODO add your handling code here:
        ShowJPanels(new Longitudes());
    }//GEN-LAST:event_btnMedidasActionPerformed

    private void btnDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisasActionPerformed
        // TODO add your handling code here:
        ShowJPanels(new Divisas());
    }//GEN-LAST:event_btnDivisasActionPerformed

    private void btnTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperatureActionPerformed
        // TODO add your handling code here:
        ShowJPanels(new Temperatura());
    }//GEN-LAST:event_btnTemperatureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDraculaIJTheme.setup();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new igConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroud;
    private javax.swing.JPanel body;
    private javax.swing.JButton btnDivisas;
    private javax.swing.JButton btnMedidas;
    private javax.swing.JButton btnTemperature;
    private javax.swing.JLabel byZeckre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables

    
}
